// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcpaeqdqypuixjmopztj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjcGFlcWRxeXB1aXhqbW9wenRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Njg5OTcsImV4cCI6MjA2NDQ0NDk5N30.yH5YCxlI1Nfu3lt7wbIXFlHt5q-rq0wqbrAxX2vn7_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);